import 'dart:convert';

/// 习惯-日志关联数据模型
class HabitJournalRelation {
  const HabitJournalRelation({
    this.id,
    required this.habitId,
    required this.journalId,
    this.relationType = 'general',
    this.relationNote,
    this.weight = 1.0,
    this.isAutoGenerated = false,
    this.isConfirmed = true,
    this.tags,
    this.extraData,
    this.createdAt,
  });

  /// 关联ID
  final int? id;

  /// 习惯ID
  final int habitId;

  /// 日志ID
  final int journalId;

  /// 关联类型
  final String relationType;

  /// 关联备注
  final String? relationNote;

  /// 权重
  final double weight;

  /// 是否自动生成
  final bool isAutoGenerated;

  /// 是否已确认
  final bool isConfirmed;

  /// 标签列表（JSON字符串）
  final String? tags;

  /// 额外数据（JSON字符串）
  final String? extraData;

  /// 创建时间
  final DateTime? createdAt;

  /// 复制关联并修改部分属性
  HabitJournalRelation copyWith({
    int? id,
    int? habitId,
    int? journalId,
    String? relationType,
    String? relationNote,
    double? weight,
    bool? isAutoGenerated,
    bool? isConfirmed,
    String? tags,
    String? extraData,
    DateTime? createdAt,
  }) {
    return HabitJournalRelation(
      id: id ?? this.id,
      habitId: habitId ?? this.habitId,
      journalId: journalId ?? this.journalId,
      relationType: relationType ?? this.relationType,
      relationNote: relationNote ?? this.relationNote,
      weight: weight ?? this.weight,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      isConfirmed: isConfirmed ?? this.isConfirmed,
      tags: tags ?? this.tags,
      extraData: extraData ?? this.extraData,
      createdAt: createdAt ?? this.createdAt,
    );
  }

  /// 从数据库Map创建关联对象
  factory HabitJournalRelation.fromMap(Map<String, dynamic> map) {
    return HabitJournalRelation(
      id: map['id'] as int?,
      habitId: map['habit_id'] as int,
      journalId: map['journal_id'] as int,
      relationType: map['relation_type'] as String? ?? 'general',
      relationNote: map['relation_note'] as String?,
      weight: (map['weight'] as num?)?.toDouble() ?? 1.0,
      isAutoGenerated: (map['is_auto_generated'] as int? ?? 0) == 1,
      isConfirmed: (map['is_confirmed'] as int? ?? 1) == 1,
      tags: map['tags'] as String?,
      extraData: map['extra_data'] as String?,
      createdAt: map['created_at'] != null 
          ? DateTime.parse(map['created_at'] as String)
          : null,
    );
  }

  /// 转换为数据库Map
  Map<String, dynamic> toMap() {
    final now = DateTime.now();
    
    return {
      if (id != null) 'id': id,
      'habit_id': habitId,
      'journal_id': journalId,
      'relation_type': relationType,
      'relation_note': relationNote,
      'weight': weight,
      'is_auto_generated': isAutoGenerated ? 1 : 0,
      'is_confirmed': isConfirmed ? 1 : 0,
      'tags': tags,
      'extra_data': extraData,
      'created_at': (createdAt ?? now).toIso8601String(),
    };
  }

  /// 转换为JSON
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'habitId': habitId,
      'journalId': journalId,
      'relationType': relationType,
      'relationNote': relationNote,
      'weight': weight,
      'isAutoGenerated': isAutoGenerated,
      'isConfirmed': isConfirmed,
      'tags': tags != null ? jsonDecode(tags!) : null,
      'extraData': extraData != null ? jsonDecode(extraData!) : null,
      'createdAt': createdAt?.toIso8601String(),
    };
  }

  /// 从JSON创建关联对象
  factory HabitJournalRelation.fromJson(Map<String, dynamic> json) {
    return HabitJournalRelation(
      id: json['id'] as int?,
      habitId: json['habitId'] as int,
      journalId: json['journalId'] as int,
      relationType: json['relationType'] as String? ?? 'general',
      relationNote: json['relationNote'] as String?,
      weight: (json['weight'] as num?)?.toDouble() ?? 1.0,
      isAutoGenerated: json['isAutoGenerated'] as bool? ?? false,
      isConfirmed: json['isConfirmed'] as bool? ?? true,
      tags: json['tags'] != null 
          ? jsonEncode(json['tags'])
          : null,
      extraData: json['extraData'] != null 
          ? jsonEncode(json['extraData'])
          : null,
      createdAt: json['createdAt'] != null 
          ? DateTime.parse(json['createdAt'] as String)
          : null,
    );
  }

  /// 解析标签列表
  List<String> getTagsList() {
    if (tags == null || tags!.isEmpty) {
      return [];
    }
    
    try {
      final decoded = jsonDecode(tags!) as List;
      return decoded.cast<String>();
    } catch (e) {
      return [];
    }
  }

  /// 设置标签列表
  String? setTagsList(List<String> tagList) {
    if (tagList.isEmpty) {
      return null;
    }
    
    return jsonEncode(tagList);
  }

  /// 解析额外数据
  Map<String, dynamic>? getExtraDataMap() {
    if (extraData == null || extraData!.isEmpty) {
      return null;
    }
    
    try {
      return jsonDecode(extraData!) as Map<String, dynamic>;
    } catch (e) {
      return null;
    }
  }

  /// 设置额外数据
  String? setExtraDataMap(Map<String, dynamic>? data) {
    if (data == null || data.isEmpty) {
      return null;
    }
    
    return jsonEncode(data);
  }

  /// 获取关联类型的描述
  String getRelationTypeDescription() {
    switch (relationType.toLowerCase()) {
      case 'general':
        return '一般关联';
      case 'inspiration':
        return '启发相关';
      case 'reflection':
        return '反思记录';
      case 'challenge':
        return '挑战记录';
      case 'achievement':
        return '成就记录';
      case 'failure':
        return '失败分析';
      case 'motivation':
        return '动机记录';
      default:
        return '未知类型';
    }
  }

  @override
  String toString() {
    return 'HabitJournalRelation(id: $id, habitId: $habitId, '
           'journalId: $journalId, relationType: $relationType, '
           'weight: $weight, isConfirmed: $isConfirmed)';
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    
    return other is HabitJournalRelation &&
        other.id == id &&
        other.habitId == habitId &&
        other.journalId == journalId;
  }

  @override
  int get hashCode {
    return Object.hash(id, habitId, journalId);
  }
}