import 'package:json_annotation/json_annotation.dart';

part 'habit_journal_relation.g.dart';

/// 习惯-日志关联类型
enum RelationType {
  @JsonValue('general')
  general,        // 一般关联
  @JsonValue('reflection')
  reflection,     // 反思关联
  @JsonValue('goal')
  goal,           // 目标关联
  @JsonValue('progress')
  progress,       // 进度关联
  @JsonValue('milestone')
  milestone,      // 里程碑关联
  @JsonValue('challenge')
  challenge,      // 挑战关联
}

/// 关联强度
enum RelationStrength {
  @JsonValue('weak')
  weak,           // 弱关联
  @JsonValue('medium')
  medium,         // 中等关联
  @JsonValue('strong')
  strong,         // 强关联
}

/// 关联上下文信息
@JsonSerializable()
class RelationContext {
  final String? note;                      // 关联备注
  final RelationType relationType;         // 关联类型
  final RelationStrength strength;         // 关联强度
  final Map<String, dynamic>? metadata;    // 元数据
  
  const RelationContext({
    this.note,
    required this.relationType,
    this.strength = RelationStrength.medium,
    this.metadata,
  });
  
  factory RelationContext.fromJson(Map<String, dynamic> json) => _$RelationContextFromJson(json);
  Map<String, dynamic> toJson() => _$RelationContextToJson(this);
  
  /// 创建一般关联上下文
  factory RelationContext.general({String? note}) => RelationContext(
    relationType: RelationType.general,
    note: note,
  );
  
  /// 创建反思关联上下文
  factory RelationContext.reflection({String? note}) => RelationContext(
    relationType: RelationType.reflection,
    strength: RelationStrength.strong,
    note: note,
  );
  
  /// 创建目标关联上下文
  factory RelationContext.goal({String? note}) => RelationContext(
    relationType: RelationType.goal,
    strength: RelationStrength.strong,
    note: note,
  );
  
  /// 创建进度关联上下文
  factory RelationContext.progress({String? note}) => RelationContext(
    relationType: RelationType.progress,
    strength: RelationStrength.medium,
    note: note,
  );
  
  /// 复制并更新上下文
  RelationContext copyWith({
    String? note,
    RelationType? relationType,
    RelationStrength? strength,
    Map<String, dynamic>? metadata,
  }) {
    return RelationContext(
      note: note ?? this.note,
      relationType: relationType ?? this.relationType,
      strength: strength ?? this.strength,
      metadata: metadata ?? this.metadata,
    );
  }
  
  /// 获取类型描述
  String get typeText {
    switch (relationType) {
      case RelationType.general:
        return '一般关联';
      case RelationType.reflection:
        return '反思记录';
      case RelationType.goal:
        return '目标相关';
      case RelationType.progress:
        return '进度更新';
      case RelationType.milestone:
        return '里程碑';
      case RelationType.challenge:
        return '挑战记录';
    }
  }
  
  /// 获取强度描述
  String get strengthText {
    switch (strength) {
      case RelationStrength.weak:
        return '弱关联';
      case RelationStrength.medium:
        return '中等关联';
      case RelationStrength.strong:
        return '强关联';
    }
  }
  
  /// 获取强度颜色（用于UI显示）
  String get strengthColor {
    switch (strength) {
      case RelationStrength.weak:
        return '#E0E0E0';     // 浅灰色
      case RelationStrength.medium:
        return '#FFB74D';     // 橙色
      case RelationStrength.strong:
        return '#4CAF50';     // 绿色
    }
  }
}

/// 习惯-日志关联模型
@JsonSerializable()
class HabitJournalRelation {
  final int? id;
  final int habitId;
  final int journalId;
  
  // 关联上下文
  final RelationContext context;
  
  // 关联权重（用于排序和筛选）
  final double weight;
  
  // 是否自动创建的关联
  final bool isAutoGenerated;
  
  // 是否已确认的关联
  final bool isConfirmed;
  
  // 关联标签（可选）
  final List<String> tags;
  
  // 扩展数据
  final Map<String, dynamic>? extraData;
  
  // 时间戳
  final DateTime createdAt;
  final DateTime? updatedAt;
  
  const HabitJournalRelation({
    this.id,
    required this.habitId,
    required this.journalId,
    required this.context,
    this.weight = 1.0,
    this.isAutoGenerated = false,
    this.isConfirmed = true,
    this.tags = const [],
    this.extraData,
    required this.createdAt,
    this.updatedAt,
  });
  
  factory HabitJournalRelation.fromJson(Map<String, dynamic> json) => _$HabitJournalRelationFromJson(json);
  Map<String, dynamic> toJson() => _$HabitJournalRelationToJson(this);
  
  /// 创建新的关联关系
  factory HabitJournalRelation.create({
    required int habitId,
    required int journalId,
    RelationContext? context,
    double weight = 1.0,
    bool isAutoGenerated = false,
    bool isConfirmed = true,
    List<String>? tags,
    Map<String, dynamic>? extraData,
  }) {
    final now = DateTime.now();
    return HabitJournalRelation(
      habitId: habitId,
      journalId: journalId,
      context: context ?? RelationContext.general(),
      weight: weight,
      isAutoGenerated: isAutoGenerated,
      isConfirmed: isConfirmed,
      tags: tags ?? [],
      extraData: extraData,
      createdAt: now,
    );
  }
  
  /// 创建自动生成的关联
  factory HabitJournalRelation.autoGenerated({
    required int habitId,
    required int journalId,
    RelationType relationType = RelationType.general,
    double weight = 0.5,
    String? note,
  }) {
    return HabitJournalRelation.create(
      habitId: habitId,
      journalId: journalId,
      context: RelationContext(
        relationType: relationType,
        strength: RelationStrength.weak,
        note: note,
      ),
      weight: weight,
      isAutoGenerated: true,
      isConfirmed: false,
    );
  }
  
  /// 创建强关联
  factory HabitJournalRelation.strong({
    required int habitId,
    required int journalId,
    RelationType relationType = RelationType.reflection,
    String? note,
  }) {
    return HabitJournalRelation.create(
      habitId: habitId,
      journalId: journalId,
      context: RelationContext(
        relationType: relationType,
        strength: RelationStrength.strong,
        note: note,
      ),
      weight: 2.0,
    );
  }
  
  /// 复制并更新关联
  HabitJournalRelation copyWith({
    int? id,
    int? habitId,
    int? journalId,
    RelationContext? context,
    double? weight,
    bool? isAutoGenerated,
    bool? isConfirmed,
    List<String>? tags,
    Map<String, dynamic>? extraData,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return HabitJournalRelation(
      id: id ?? this.id,
      habitId: habitId ?? this.habitId,
      journalId: journalId ?? this.journalId,
      context: context ?? this.context,
      weight: weight ?? this.weight,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      isConfirmed: isConfirmed ?? this.isConfirmed,
      tags: tags ?? this.tags,
      extraData: extraData ?? this.extraData,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? DateTime.now(),
    );
  }
  
  /// 确认自动生成的关联
  HabitJournalRelation confirm({
    RelationStrength? strength,
    String? note,
  }) {
    return copyWith(
      isConfirmed: true,
      context: context.copyWith(
        strength: strength ?? RelationStrength.medium,
        note: note ?? context.note,
      ),
      weight: strength == RelationStrength.strong ? 2.0 : 
              strength == RelationStrength.weak ? 0.5 : 1.0,
    );
  }
  
  /// 拒绝自动生成的关联（实际上是软删除）
  HabitJournalRelation reject() {
    return copyWith(
      weight: 0.0,
      isConfirmed: false,
      extraData: {
        ...?extraData,
        'rejected': true,
        'rejectedAt': DateTime.now().toIso8601String(),
      },
    );
  }
  
  /// 是否为有效关联
  bool get isValid => weight > 0 && !isRejected;
  
  /// 是否被拒绝
  bool get isRejected => extraData?['rejected'] == true;
  
  /// 是否需要用户确认
  bool get needsConfirmation => isAutoGenerated && !isConfirmed;
  
  /// 获取关联描述
  String get description {
    final buffer = StringBuffer();
    
    if (isAutoGenerated) {
      buffer.write('自动关联 - ');
    }
    
    buffer.write(context.typeText);
    
    if (context.note?.isNotEmpty == true) {
      buffer.write(': ${context.note}');
    }
    
    return buffer.toString();
  }
  
  /// 获取权重等级
  String get weightLevel {
    if (weight >= 2.0) return '高';
    if (weight >= 1.0) return '中';
    if (weight >= 0.5) return '低';
    return '无效';
  }
  
  /// 是否包含特定标签
  bool hasTag(String tag) {
    return tags.contains(tag);
  }
  
  /// 添加标签
  HabitJournalRelation addTag(String tag) {
    if (hasTag(tag)) return this;
    return copyWith(tags: [...tags, tag]);
  }
  
  /// 移除标签
  HabitJournalRelation removeTag(String tag) {
    if (!hasTag(tag)) return this;
    return copyWith(tags: tags.where((t) => t != tag).toList());
  }
  
  /// 计算关联评分（用于排序）
  double get score {
    double baseScore = weight;
    
    // 强度加成
    switch (context.strength) {
      case RelationStrength.weak:
        baseScore *= 0.7;
        break;
      case RelationStrength.medium:
        baseScore *= 1.0;
        break;
      case RelationStrength.strong:
        baseScore *= 1.5;
        break;
    }
    
    // 确认状态加成
    if (!isConfirmed) {
      baseScore *= 0.5;
    }
    
    // 自动生成的关联降权
    if (isAutoGenerated) {
      baseScore *= 0.8;
    }
    
    // 有备注的关联加分
    if (context.note?.isNotEmpty == true) {
      baseScore *= 1.1;
    }
    
    return baseScore;
  }
  
  /// 格式化创建时间
  String get formattedCreatedTime {
    return '${createdAt.year}-${createdAt.month.toString().padLeft(2, '0')}-${createdAt.day.toString().padLeft(2, '0')} ${createdAt.hour.toString().padLeft(2, '0')}:${createdAt.minute.toString().padLeft(2, '0')}';
  }
  
  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HabitJournalRelation &&
          runtimeType == other.runtimeType &&
          habitId == other.habitId &&
          journalId == other.journalId;

  @override
  int get hashCode => habitId.hashCode ^ journalId.hashCode;
  
  @override
  String toString() {
    return 'HabitJournalRelation{id: $id, habitId: $habitId, journalId: $journalId, type: ${context.relationType}, confirmed: $isConfirmed}';
  }
}